import DefaultLayout from "@/components/DefaultLayout";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design by Lakyu",
  description: "Generated by love for life",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
